// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoboticArmSim.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("RoboticArmSim.Models.MovementLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Angle")
                        .HasColumnType("REAL");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Joint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RobotArmId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RobotArmId");

                    b.HasIndex("UserId");

                    b.ToTable("MovementLogs");
                });

            modelBuilder.Entity("RoboticArmSim.Models.RobotArm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("JointAngles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<float>("PositionZ")
                        .HasColumnType("REAL");

                    b.Property<float>("Rotation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RobotArms");
                });

            modelBuilder.Entity("RoboticArmSim.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsControlling")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCommandTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoboticArmSim.Models.MovementLog", b =>
                {
                    b.HasOne("RoboticArmSim.Models.RobotArm", "RobotArm")
                        .WithMany()
                        .HasForeignKey("RobotArmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoboticArmSim.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("RobotArm");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
